config/routes.rb
Rails.application.routes.draw do
  root "posts#index" 
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at desc")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(params[:post].permit(:title, :content))
    redirect_to action: "index"
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params[:post].permit(:title, :content))
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to action: "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://tinyurl.com/codesensei" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "New post", "/posts/new" %>
    <%= link_to "All posts", "/" %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>New post</h2>

<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h2>All posts</h2>

<% @posts.each do |post| %>
  <h3>
      <%= link_to post.title, post_path(post) %>
      <%= link_to "Delete", post_path(post), method: :delete %>
  </h3>
<% end %>

app/views/posts/new.html.erb
<h2>New post</h2>

<%= form_for @post do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p>
  <%= @post.content %>
</p>

<p>
  <%= link_to "Edit", edit_post_path(@post) %>
</p>

<p>
  <%= link_to "Share", "https://www.facebook.com/sharer/sharer.php?" +
  {
    u: post_url(@post),
    quote: "Moja pierwsza aplikacja z Code Sensei",
    title: @post.title
  }.to_param
  %>
</p>